export const VENEZUELA_STATES = [
  'Amazonas',
  'Anzoátegui',
  'Apure',
  'Aragua',
  'Barinas',
  'Bolívar',
  'Carabobo',
  'Cojedes',
  'Delta Amacuro',
  'Distrito Capital',
  'Falcón',
  'Guárico',
  'Lara',
  'Mérida',
  'Miranda',
  'Monagas',
  'Nueva Esparta',
  'Portuguesa',
  'Sucre',
  'Táchira',
  'Trujillo',
  'La Guaira (Vargas)',
  'Yaracuy',
  'Zulia',
]

// Ciudades principales por estado (para autocompletar)
export const CITIES_BY_STATE: Record<string, string[]> = {
  'Distrito Capital': ['Caracas'],
  'Miranda': ['Los Teques', 'Guarenas', 'Guatire', 'Charallave', 'Ocumare del Tuy', 'Petare'],
  'Aragua': ['Maracay', 'La Victoria', 'Turmero', 'Villa de Cura', 'Cagua'],
  'Carabobo': ['Valencia', 'Puerto Cabello', 'Guacara', 'San Diego', 'Naguanagua'],
  'Zulia': ['Maracaibo', 'Cabimas', 'Ciudad Ojeda', 'San Francisco', 'Punto Fijo'],
  'Lara': ['Barquisimeto', 'Carora', 'El Tocuyo', 'Quíbor'],
  'Anzoátegui': ['Barcelona', 'Puerto La Cruz', 'El Tigre', 'Anaco', 'Lecherías'],
  'Bolívar': ['Ciudad Bolívar', 'Puerto Ordaz', 'San Félix', 'Upata'],
  'Táchira': ['San Cristóbal', 'Táriba', 'Rubio', 'La Fría'],
  'Mérida': ['Mérida', 'El Vigía', 'Ejido', 'Tovar'],
  'Monagas': ['Maturín', 'Caripito', 'Punta de Mata'],
  'Sucre': ['Cumaná', 'Carúpano', 'Güiria'],
  'Falcón': ['Coro', 'Punto Fijo', 'La Vela de Coro'],
  'Portuguesa': ['Guanare', 'Acarigua', 'Araure'],
  'Barinas': ['Barinas', 'Barinitas', 'Socopó'],
  'Trujillo': ['Trujillo', 'Valera', 'Pampán'],
  'Yaracuy': ['San Felipe', 'Yaritagua', 'Chivacoa'],
  'Nueva Esparta': ['La Asunción', 'Porlamar', 'Juan Griego', 'Pampatar'],
  'Guárico': ['San Juan de los Morros', 'Valle de la Pascua', 'Calabozo'],
  'Cojedes': ['San Carlos', 'Tinaquillo'],
  'Apure': ['San Fernando de Apure', 'Guasdualito'],
  'Amazonas': ['Puerto Ayacucho'],
  'Delta Amacuro': ['Tucupita'],
  'La Guaira (Vargas)': ['La Guaira', 'Maiquetía', 'Catia La Mar'],
}
